### PR TITLE
Add logging builds (from special builds)

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Logging builds are useful for debugging. See https://nsis.sourceforge.io/Special_Builds. I am also adding myself as a maintainer.

### CODE REVIEW

**Comment by dbast** [comment]
Logging builds are e.g. used in the [constructor](https://github.com/conda/constructor) tests for debugging.

The manual download from sourceforge there is not really reliable. Having it as conda package would improve that situation.

@conda-forge/nsis ready for review. thanks

**Comment by jaimergp** [comment]
A week has passed with no answer. I am merging!

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@jaimergp, there were issues identified by @isuruf in the last PR that are not addressed. Think those should be handled before merging new things. Have raised an issue to track this ( https://github.com/conda-forge/nsis-feedstock/issues/23 )

**Pull request merged**
